<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AiGarden.AiService.Core\AiGarden.AiService.Core.csproj" />
		<ProjectReference Include="..\AiGarden.AiService.UseCases\AiGarden.AiService.UseCases.csproj" />
		<ProjectReference Include="..\AiGarden.AiService.Infrastructure\AiGarden.AiService.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\shared\AiGarden.BuildingBlocks\AiGarden.BuildingBlocks.csproj" />
		<ProjectReference Include="..\..\..\shared\AiGarden.Contracts\AiGarden.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
	</ItemGroup>
</Project>
